name := "TopicModeling"
version := "1.0"
libraryDependencies += "org.apache.spark" %% "spark-core" % "1.3.1"
libraryDependencies += "org.apache.spark" %% "spark-mllib" % "1.3.1"
resolvers += "Akka Repository" at "http://repo.akka.io/releases/"
